version: '3.8'

services:
  pomaiwhiteboard-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pomaiwhiteboard-frontend
    ports:
      - "3003:80"
    restart: always
    networks:
      - pomaieco_network

networks:
  pomaieco_network:
    external: true
